### ISSUE TITLE
Selecting menu options crash the program

### ISSUE THREAD

**Issue by kokujin** [Pomax/terminal-menu-program#5]
Using the example from the website

```
var builder = require("terminal-menu-program"),
    program = new builder.Program("Test program"),

// single screen definition
menu = program.menu("main");
menu.text("A Terminal Menu Program");
menu.spacer();
menu.option("menu switch (going to this screen when selected)", "main");
menu.spacer();
menu.check("a toggle option", function(state) { /* ... */ });
menu.check("a checked toggle option", true);
menu.check("a checked toggle callback", true, function(state) {
    console.log(state);
 });
menu.spacer();
menu.cancel("exit", function() { program.halt(); process.exit(0); });

// run single screen program
program.run("main");
```

Start the program, selecting either one of the checkboxes or the menu switch option 3 or 4 times in succession crashes the program.

**Comment by Pomax** [comment]
Associated error log:
```
events.js:85
      listeners[i].call(self);
                  ^

TypeError: Cannot read property 'call' of undefined
    at emitNone (events.js:85:19)
    at Stream.emit (events.js:179:7)
    at Stream.Charm.end (J:\Junctions\Users\Mike\Documents\Git projects\temp\_\node_modules\charm\index.js:107:10)
    at Menu.close (J:\Junctions\Users\Mike\Documents\Git projects\temp\_\node_modules\terminal-menu\index.js:119:16)
    at Object.Menu.close (J:\Junctions\Users\Mike\Documents\Git projects\temp\_\node_modules\terminal-menu-program\menu.js:46:17)
    at Object.Menu.draw (J:\Junctions\Users\Mike\Documents\Git projects\temp\_\node_modules\terminal-menu-program\menu.js:139:10)
    at Object.Menu.handler (J:\Junctions\Users\Mike\Documents\Git projects\temp\_\node_modules\terminal-menu-program\menu.js:106:21)
    at emitTwo (events.js:100:13)
    at Menu.emit (events.js:185:7)
    at Menu.ondata [as _ondataHandler] (J:\Junctions\Users\Mike\Documents\Git projects\temp\_\node_modules\terminal-menu\index.js:202:14)
```

**Comment by Pr0Wolf29** [comment]
Selecting the same item twice does it. If you select it, and then go up or down, and then back to it, it works.

**Comment by Pr0Wolf29** [comment]
Actually yeah the 4th time is what causes the crash.

**Comment by Pomax** [comment]
Probably worth using something like [curses](https://www.npmjs.com/package/curses) at this point, as I no longer use this package myself (PRs that fix it are entirely welcome, but I will not be investing time in this myself outside of reviewing PRs and merging those in)

**Comment by str3tch** [comment]
I also see this error.. shame I can't figure out how to fix it, the menu is a lovely idea and I want to use it! but can't :(
